MVC4Events/Controllers/EventsController.cs
using mvc4events.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Unconnected.Mvc.Outputcache;

namespace mvc4events.Controllers
{
    public class EventsController : Controller
    {

        private EventsRepository _eventList = null;

        public EventsController(EventsRepository eventList)
        {
            this._eventList = eventList;
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Event List";
            return View();
        }

        //[OutputCache(CacheProfile = "EventsCache")]
        //[OutputCache(Duration =3600, VaryByParam = "iDisplayStart; iDisplayLength; sSearch")]
        //[ActionResultCache(Duration = 3600, VaryByParam = "iDisplayStart; iDisplayLength; sSearch")]
        //[ActionResultCache(CacheProfile = "EventsCache")]
        [ParameterizedOutputCacheAttribute(CacheProfile = "EventsCache")]
        [HttpPost]
        public JsonResult getEvents(int iDisplayStart, int iDisplayLength, string sSearch)
        {

            sSearch = sSearch.ToLower(); // Force No case sensitive
            //List<Event> eventList = this._eventList.GetEvents().ToList();
            var eventList = this._eventList.GetEvents().AsQueryable();

            int totalRecord = eventList.Count();
            if (iDisplayLength == -1) { iDisplayLength = totalRecord; }



            if (!string.IsNullOrEmpty(sSearch))
                eventList = eventList.Where(x => x.Title.ToLower().Contains(sSearch)
                || x.Technology.ToLower().Contains(sSearch)
                );

            int TotalDisplayRecords = eventList.Count();

            eventList = eventList.OrderBy(x => x.Title).Skip(iDisplayStart).Take(iDisplayLength);

            var data = new {
                sEcho = 0,
                iTotalRecords = totalRecord,
                iTotalDisplayRecords = TotalDisplayRecords,
                aaData = eventList.ToList()
            };

            return Json(data);
        }


        #region ConfigurationPropertyGets
        [System.Configuration.ConfigurationProperty("varyByParam")]
        public string VaryByParam { get; set; }
        [System.Configuration.ConfigurationProperty("outputCacheSettings")]
        public System.Web.Configuration.OutputCacheSettingsSection OutputCacheSettings { get; } 
        #endregion

    }
}

MVC4Events/Controllers/EventsMemCacheController.cs
using mvc4events.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Runtime.Caching;

namespace mvc4events.Controllers
{
    public class EventsMemCacheController : Controller
    {

        private EventsRepository _eventList = null;

        public EventsMemCacheController(EventsRepository eventList)
        {
            this._eventList = eventList;
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Event List";
            return View();
        }


        [HttpPost]
        public JsonResult getEvents(int sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            string querykey = JsonConvert.SerializeObject(new { iDisplayStart, iDisplayLength, sSearch });

            ObjectCache cache = MemoryCache.Default;
            CacheItemPolicy cacheItemPolicy = new CacheItemPolicy();
            cacheItemPolicy.AbsoluteExpiration = new DateTimeOffset(DateTime.Now.AddHours(1));

            dynamic list=cache.Get(querykey);
            if (list != null) // There is data in the cache for given parameters
            {                
                return Json(new {
                    sEcho = sEcho,
                    iTotalRecords = list.iTotalRecords,
                    iTotalDisplayRecords = list.iTotalDisplayRecords,
                    aaData = list.aaData
                });
            }
            else // There is no data in the cache for given parameters
            { 
                sSearch = sSearch.ToLower(); // Force No case sensitive
                
                var eventList = this._eventList.GetEvents().AsQueryable();
                
                int totalRecord = eventList.Count();
                if (iDisplayLength == -1) { iDisplayLength = totalRecord; }


                if (!string.IsNullOrEmpty(sSearch))
                    eventList = eventList.Where(x => x.Title.ToLower().Contains(sSearch)
                    || x.Technology.ToLower().Contains(sSearch)
                    );

                int TotalDisplayRecords = eventList.Count();

                eventList = eventList.OrderBy(x => x.Title).Skip(iDisplayStart).Take(iDisplayLength);            

                var data = new {
                    sEcho = sEcho,
                    iTotalRecords = totalRecord,
                    iTotalDisplayRecords = TotalDisplayRecords,
                    aaData = eventList.ToList()
                };
                

                cache.Add(querykey, data, cacheItemPolicy);
                return Json(data);
            }            
        }


        #region ConfigurationPropertyGets
        [System.Configuration.ConfigurationProperty("varyByParam")]
        public string VaryByParam { get; set; }
        [System.Configuration.ConfigurationProperty("outputCacheSettings")]
        public System.Web.Configuration.OutputCacheSettingsSection OutputCacheSettings { get; } 
        #endregion

    }
}

MVC4Events/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Events App</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link crossorigin="anonymous" href="https://cdn.datatables.net/1.9.4/css/jquery.dataTables.css" />
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("MVC Events", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Events (w/Outputcache)", "Index", "Events")</li>
                        <li>@Html.ActionLink("Events (w/memoryCache)", "Index", "EventsMemCache")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    <script crossorigin="anonymous" src="https://cdn.datatables.net/1.9.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>